### ISSUE TITLE
"Invalid input" error

### ISSUE THREAD

**Issue by MuffinWithJam** [futurepress/epubjs-rn#1]
Got this after placing the line `<Reader src={"https://s3.amazonaws.com/moby-dick/OPS/package.opf"} paginated={true} location={0}/>`

![img_0499](https://cloud.githubusercontent.com/assets/11280671/18232573/cb916d1e-72da-11e6-9ef6-c54d50c6d95d.PNG)

**Comment by Ileezyy** [comment]
> Got this after placing the line Reader src={"https://s3.amazonaws.com/moby-dick/OPS/package.opf"} paginated={true} location={0}/

@fchasen, the same here =(

**Comment by fchasen** [comment]
Sorry about that, upgrade didn't go correctly. 

I've rebuilt the project with RN v0.37 and epub.js fixed to https://github.com/futurepress/epub.js/tree/ad26711cb4a276f2e048d504168223f4c7a1a259

I'll switch the package to pull epubjs v0.3 from npm in the next week or so.

**Comment by Ileezyy** [comment]
> I'll switch the package to pull epubjs v0.3 from npm in the next week or so.

Great! Thank you so much, Fred. Project is really brilliant.
