### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by Guildsmac** [futurepress/epubjs-rn#101]
Can someone please help me? This epub reader is the last part of my app, and i'm trying to run the exact same example from the src code but i'm getting this erros: 
![error](https://user-images.githubusercontent.com/15653194/46249132-7bbca100-c3fa-11e8-8e9b-4ef0feb162bf.png)

**Comment by LuisRodriguezLD** [comment]
what was the fix?

**Comment by fchasen** [comment]
https://github.com/joltup/rn-fetch-blob/issues/244
