### ISSUE TITLE
Trigger if cfi was seen

### ISSUE THREAD

**Issue by Kozyyy** [futurepress/epubjs-rn#106]
My Use-Case: When user reaches specific cfi, app handles it with some interactivity.

Is it possible to find out if specific cfi is on the screen?

**Comment by fchasen** [comment]
`onLocationChange  will provide the start and end cfi's that are visible.

Since CFIs are sequential, you can use `EpubCFI.compare(a, b)` from `epubjs` to check if your CFI is greater than the start and less than the end.
