### ISSUE TITLE
Current page

### ISSUE THREAD

**Issue by zkenes** [futurepress/epubjs-rn#11]
I've tried a lot, but I can't figure out how to get current page. Can anyone help me?

**Comment by nhutnguyen1988** [comment]
me too, can't figure out how to get current page
need a props type to show/hide page number

**Comment by fchasen** [comment]
You can get the current page by passing a function to the `onLocationChange` property.

It will return an object with the CFI, location in the book and the percentage complete.

**Comment by imarem** [comment]
Hi @fchasen ,

On the onLocationChange event, I only get this params:
end;"epubcfi(/6/6[chapter-1]!/4/2/112/1:322)"
href:"chapter-1.xhtml"
index:2
percentage:0.5384615384615384
start:"epubcfi(/6/6[chapter-1]!/4/2/110/3:137)"

How can I get the currentpage from the start field's CFI?

This link [https://github.com/futurepress/epub.js/wiki/Tips-and-Tricks] talks about how to get the current page. Are you generate pagination this purpose or is there any alternative to get the current page?

Thanks in advance.

**Comment by imarem** [comment]
Hi @zkenes @nhutnguyen1988 ,

Now with 0.080 version, you can get the currentPage on property onLocationChange, this way

onLocationChange={(visibleLocation) => {
  console.log("currentPage", visibleLocation.start.displayed.page);
}} 

Thanks @fchasen for the las update!!!

**Comment by fchasen** [comment]
Location is equivalent to a kindle / adobe page location, otherwise if you want the rendered paged you can use the displayed pages to show what page you are in for that chapter.

Generate pagination shouldn't be used on the client as it has to render the entire book.
