### ISSUE TITLE
load file from internal storage with react-native-fetch-blob

### ISSUE THREAD

**Issue by veeyka** [futurepress/epubjs-rn#110]
hello
i have downloaded this two files with react-native-fetch-blob
and i want to open this files with epubjs-en.
i have 2 file here 
1 : RNFB.fs.dirs.DocumentDir/epubfile.epub
2 : RNFB.fs.dirs.DocumentDir/pakcage.opf

how to access  them
streamer check metod always returns false for existing 
Hoping you'd take a look. Thanks!

**Comment by ssaigal** [comment]
Hi were you able to solve this if so please tell the way to do it.
Thanks
