### ISSUE TITLE
font family

### ISSUE THREAD

**Issue by veeyka** [futurepress/epubjs-rn#118]
hey guys
can someone answer my question ???
font-family inside body and epub font property is not changing font
it's 2 week i'm working on it and try out every way get in my head.
its not working really
can someone just say yes or no
just tell me if it's not working
i'm on react-native 0.57.8
and epub-rn version 0.0.127

**Comment by veeyka** [comment]
i fixed font-family
and i will close this one
you need add font family in css body of theme in epub
then add all of your fonts to the epub file when you build epub file
i use sigil application to create a epub book
there you need to add fonts and add a stylesheet css file and also add file to the epub header codes
and a css @font-face to style file
you can call any font in react-native when you have added that font to epub file when you created it.

**Comment by mesismart** [comment]
hi veeyka , can you send me your sample code for change theme
