### ISSUE TITLE
Local path to epub

### ISSUE THREAD

**Issue by MuffinWithJam** [futurepress/epubjs-rn#12]
How should I write `<Epub />` "src" parameter to open local epub file on IOS device?
For example, I have path:

 `/Users/admin/Library/Developer/CoreSimulator/Devices/06984DB8-F123-4B6B-9EC1-328CD86A4FDA/data/Containers/Data/Application/148A7607-DEC7-4705-A24B-027BF3985EF6/Documents/1.epub`

but file hasn't being opened.

The path starting with "file://" also doesn't work.

**Comment by fchasen** [comment]
Sadly passing a local path won't work as the assets need to be serve to the webview.
I've added a static server in the example app to work with local files.
