### ISSUE TITLE
EpubReader demo run failed

### ISSUE THREAD

**Issue by nhutnguyen1988** [futurepress/epubjs-rn#13]
Hi, I downloaded your EpubReader demo and 
1. run 'npm install'
2. react-native link
3. then I run on android emulator and get error (see the image)

<img width="1680" alt="screen shot 2017-02-14 at 8 42 26 am" src="https://cloud.githubusercontent.com/assets/25758427/22915777/2f5ab2be-f2ac-11e6-8c10-56a9b7b6eafe.png">
<img width="727" alt="screen shot 2017-02-14 at 8 42 35 am" src="https://cloud.githubusercontent.com/assets/25758427/22915778/2f5cd71a-f2ac-11e6-9b20-64def93635c2.png">

I need help, please
Thanks

**Comment by matiasgq** [comment]
@nhutnguyen1988  I have the same error

**Comment by fchasen** [comment]
Sorry about that, I've switched to precompiling the components so you shouldn't get this issue anymore.

**Comment by imarem** [comment]
@fchasen I have the same error. I downloaded the example today, any ideas to fix the issue?

Thanks

**Comment by nhutnguyen1988** [comment]
Guys, I add more dependencies in my app package.json, its work perfectly, Im run on Mac

{
  "name": "EpubReader",
  "version": "0.0.1",
  "description" : "Demo of Epubjs React Native components",
  "repository": "https://github.com/futurepress/epubjs-rn",
  "main": "components/index.js",
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "clean" : "watchman watch-del-all",
    "reset" : "npm run clean && node node_modules/react-native/local-cli/cli.js start -- --resetCache"
  },
  "license": "BSD-2-Clause",
  "dependencies": {
    "react": "~15.4.1",
    "react-native": "0.40.0",
    "epubjs-rn": "0.0.29",
    "react-native-visible-scrollview": "0.0.1",
    "buffer": "^5.0.1",
    "epubjs": "0.3.11",
    "events": "^1.1.1",
    "jszip": "^3.1.1",
    "lodash": "^4.14.0",
    "path-webpack": "0.0.2",
    "react-native-fetch-blob": "0.10.2-beta.8",
    "react-native-orientation": "github:8fit/react-native-orientation",
    "react-native-webview-bridge": "^0.33.0",
    "stream": "0.0.2",
    "stream-browserify": "^2.0.1",
    "util": "^0.10.3"
  },
  "devDependencies": {
    "babel-jest": "18.0.0",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "18.1.0",
    "jest-react-native": "18.0.0",
    "react-test-renderer": "~15.4.1",
    "babel-cli": "^6.18.0",
    "babel-loader": "^6.2.9",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-module-resolver": "^2.3.0",
    "babel-plugin-static-fs": "^1.1.0",
    "babel-polyfill": "^6.16.0",
    "babel-preset-env": "1.0.2",
    "babel-preset-es2015": "^6.18.0",
    "babili-webpack-plugin": "0.0.7",
    "gulp": "^3.9.1",
    "gulp-babel": "^6.1.2",
    "gulp-plumber": "^1.1.0",
    "gulp-util": "^3.0.8",
    "react": "~15.4.1",
    "react-native": "0.39.2",
    "webpack": "^1.14.0"
  },
  "jest": {
    "preset": "jest-react-native"
  }
}
