### ISSUE TITLE
【Android】The call to open() method is found to throw an exception with the message: Empty Response

### ISSUE THREAD

**Issue by cllemon** [futurepress/epubjs-rn#134]
##### The call to open() method is found to throw an exception with the message:

```js
GET http://localhost:3737/25d4e315cd8b4c53f8144bff19573c9f/META-INF/container.xml net::ERR_CONNECTION_REFUSED

{
   message: "Empty Response",
   stack:  "Error↵    at XMLHttpRequest.handler (blob:file:///1aa186e1-6def-49ad-a169- 
             575a761dc351:146702:22)",
   status:0
}
```

#####  Release notes：

- "epubjs-rn": "^0.1.1",
- "react-native": "0.58.6",

#####   I hope to get the author's reply. Thank you very much！

**Comment by cllemon** [comment]
#### The book file can still be read after the above error, but because open() throws an exception, the onLocationsReady()/onReady() hook function will not execute, causing the navigation object to be undefined, which I find confusing.

**Comment by Ansalibrahim** [comment]
@cllemon is issue solved? I am stuck on this. Could you please help me out?

**Comment by startblingbling** [comment]
@cllemon  I am getting the same error，Could you please tell me how did you solve it?

**Comment by mesismart** [comment]
any answer?

**Comment by lyseiha** [comment]
+1
