### ISSUE TITLE
I do not work the components in my project

### ISSUE THREAD

**Issue by matiasgq** [futurepress/epubjs-rn#14]
Hello, I am trying to install the components to use them in my project, but when ever I install it it generates error 500 "Unable to resolve module epubjs-rn"
It only works for me if I download the complete project, and install it from there, but I need to use it in my own project

Anyone having the same problem?

**Comment by fchasen** [comment]
I think you might just need to reset the packager.

Try running:
```
watchman watch-del-all
node node_modules/react-native/local-cli/cli.js start -- --resetCache
```
