### ISSUE TITLE
npm run failed to compile

### ISSUE THREAD

**Issue by clarodanesh** [futurepress/epubjs-rn#142]
I am making a React Native app managed with expo. I am trying to incorporate epubjs into the app however after following the installation steps I get the following error when running the command ```npm run web``` or ```npm run android```

```
C:/Users/Username/Documents/GitHub/test-epub-reader/node_modules/rn-fetch-blob/index.js 12:12
Module parse failed: Unexpected token (12:12)
You may need an appropriate loader to handle this file type.
|   AppState,
| } from 'react-native'
> import type {
|   RNFetchBlobNative,
|   RNFetchBlobConfig,
```

**Comment by clarodanesh** [comment]
Closed this as I realised this may not be a problem with epubjs-rn

**Comment by batelhi** [comment]
Any advice to solve this error on Expo app?
