### ISSUE TITLE
android 9 api 28 bug

### ISSUE THREAD

**Issue by erickbank** [futurepress/epubjs-rn#144]
Epubjs-rn is not working with devices on android 9 , it loads on debug and simulator mode , but on release mode , stays in continuous loading.

**Comment by oakcreations** [comment]
any solution ? @fchasen

**Comment by Rickpariz** [comment]
any solution ? @JakeHartnell

**Comment by Penglenghok** [comment]
you need to add this permisssion to android AndroidManifest.xml 
" android:usesCleartextTraffic="true" "

**Comment by Uysim** [comment]
Meet the same problem anyone managed to fixed it?

**Comment by erickbank** [comment]
@Uysim as @Penglenghok Said , Just add " android:usesCleartextTraffic="true"  on AndroidManifest.xml , it will work like charm.
