### ISSUE TITLE
Android: EpubReader demo run failed

### ISSUE THREAD

**Issue by imarem** [futurepress/epubjs-rn#16]
Hi, I downloaded the EpubReader demo, run 'npm install', react-native link and when run in a device i get the error 

![screenshot_20170224-165957](https://cloud.githubusercontent.com/assets/4670453/23310742/d3a1d28a-fab3-11e6-8504-1ff3be423be4.png)

Any ideas for fix this issue?
Thanks for advance!!

**Comment by nhutnguyen1988** [comment]
I add more dependencies in my app package.json, its work perfectly, Im run on Mac

{
"name": "EpubReader",
"version": "0.0.1",
"description" : "Demo of Epubjs React Native components",
"repository": "https://github.com/futurepress/epubjs-rn",
"main": "components/index.js",
"scripts": {
"start": "node node_modules/react-native/local-cli/cli.js start",
"test": "jest",
"clean" : "watchman watch-del-all",
"reset" : "npm run clean && node node_modules/react-native/local-cli/cli.js start -- --resetCache"
},
"license": "BSD-2-Clause",
"dependencies": {
"react": "~15.4.1",
"react-native": "0.40.0",
"epubjs-rn": "0.0.29",
"react-native-visible-scrollview": "0.0.1",
"buffer": "^5.0.1",
"epubjs": "0.3.11",
"events": "^1.1.1",
"jszip": "^3.1.1",
"lodash": "^4.14.0",
"path-webpack": "0.0.2",
"react-native-fetch-blob": "0.10.2-beta.8",
"react-native-orientation": "github:8fit/react-native-orientation",
"react-native-webview-bridge": "^0.33.0",
"stream": "0.0.2",
"stream-browserify": "^2.0.1",
"util": "^0.10.3"
},
"devDependencies": {
"babel-jest": "18.0.0",
"babel-plugin-syntax-jsx": "^6.18.0",
"babel-preset-react-native": "1.9.1",
"jest": "18.1.0",
"jest-react-native": "18.0.0",
"react-test-renderer": "~15.4.1",
"babel-cli": "^6.18.0",
"babel-loader": "^6.2.9",
"babel-plugin-add-module-exports": "^0.2.1",
"babel-plugin-module-resolver": "^2.3.0",
"babel-plugin-static-fs": "^1.1.0",
"babel-polyfill": "^6.16.0",
"babel-preset-env": "1.0.2",
"babel-preset-es2015": "^6.18.0",
"babili-webpack-plugin": "0.0.7",
"gulp": "^3.9.1",
"gulp-babel": "^6.1.2",
"gulp-plumber": "^1.1.0",
"gulp-util": "^3.0.8",
"react": "~15.4.1",
"react-native": "0.39.2",
"webpack": "^1.14.0"
},
"jest": {
"preset": "jest-react-native"
}
}

**Comment by imarem** [comment]
Hi @nhutnguyen1988 
I apply the changes and the issue persist.

I'm using "epubjs-rn": "0.0.37" version and running in Android, 

Thanks

**Comment by nhutnguyen1988** [comment]
Hi @imarem, u use windows or mac, because, I download new "epubjs-rn": "0.0.37", and apply dependencies and install and run ok, Im build and run on macbook, my friend had the same error with you, he run on windows pc, and get error about node_module jszip like you, and he just re install a new simulator (with ARM architecture) and it work.

**Comment by imarem** [comment]
Hi @nhutnguyen1988,

Thanks for your help, I use a windows on a real device. I apply the solution you suggest and I can't fix the error.

At the moment I created the folders in the jzip library, 
"node_modules\jszip\lib\**support.j\lib\**readable-stream-browser.js" and I fix the issue...

Thanks.
