### ISSUE TITLE
problem after installing:  Unable to resolve module `epubjs-rn`

### ISSUE THREAD

**Issue by valinaga** [futurepress/epubjs-rn#17]
I follow the instructions for instalation but I got this error when running the ios.

UnableToResolveError: Unable to resolve module `epubjs-rn` from `/Users/vali/MyWorks/react/humanitas/App/Containers/PresentationScreen.js`: Module does not exist in the module map or in these directories:
  /Users/vali/MyWorks/react/humanitas/node_modules
,   /Users/vali/node_modules

Any help appreciated!
Thanks

**Comment by manuvo** [comment]
For me is the same.

**Comment by patyk** [comment]
Same here. I get the feedback on the terminal about unmet peer dependency for react-native v0.40 (I was using 0.41.2). But even after switching to an older version of react-native had the same error. 

It only shows up when I add in my app the  Epub import.

**Comment by patyk** [comment]
Seems to be working fine with 0.0.15, pre 8d65d60ae20d948a3221ef48badcaa95d9c8894d

**Comment by manuvo** [comment]
So?

**Comment by valinaga** [comment]
@patyk what do you mean working fine? no error for unresolved module?

**Comment by manuvo** [comment]
@patyk I installed a fresh last days ago. I didn't work it for me.

**Comment by valinaga** [comment]
It looks like there's a problem in the .babelrc file in epubjs-rn.
There's a plugin named "module-resolver" which is unknown.
But cleaning this and the subsequent errors in Epub.js like bad import "fs" probably instead of "react-native-fs" and "path" which does not exists, still didn't fix the issues, as it appears more and more errors.
Did anyone saw this component ever running? 
Does it make sense to spend time on it?

**Comment by patyk** [comment]
As the workaround I have imported Epub directly from node_modules:
import { Epub } from '../../node_modules/epubjs-rn/src/index'

and it worked. 

As I wrote due to the recent changes in package.json might have affected Epub object (commit 8d65d60ae20d948a3221ef48badcaa95d9c8894d), so I used the old path directly to src/index and not component/index file. 
Hope it helps.

**Comment by fchasen** [comment]
If you are using the files directly from this repo, (such as to run the example) you will need to run 
```
gulp build
```
otherwise the build files won't exist in the `component` file.

If you are using the components in your own app by installing from npm, they will be prebuilt.

**Comment by valinaga** [comment]
It's so frustrating. Is there any way this works?
I tried to clone the repo, and then npm install in EpubReader. Got errors, same about the plugins in .babelrc
Tried to use the epubjs-rn as a component and also same problems.
@fchasen can you please spare some minutes to write down some instruction on how to have this work?
Thanks

**Comment by imarem** [comment]
Hi @valinaga,
I think you need to install these two libraries. I had the same error and adding them I solved it

npm install babel-plugin-static-fs --save-dev
npm install --save-dev babel-plugin-module-resolver

I hope it helps.

**Comment by manuvo** [comment]
@imarem Don't work for me.

**Comment by Leafeanking** [comment]
I've been banging my head against the wall over this for two days. I finally installed `babel-plugin-static-fs`, `babel-plugin-module-resolver`, and `module-resolver` via npm and it worked. Then I realized I'm serving an Epub and the example shows an opf? Time to debug that, but I hope this helped!

**Comment by valinaga** [comment]
@Leafeanking did you manage to make it work on Android. I keep receiving the "EPUB.js not loaded".
I didn't add the module-solver. Maybe that's the reason? I'll add it and try again.

**Comment by Leafeanking** [comment]
@valinaga Sadly I'm only focused on IOS, as soon as I can get the darn thing to read an EPub from the internet I'll look into the Android version.

**Comment by JulianKingman** [comment]
For some reason the source for my `epubjs-rn` package was this github repo, which doesn't include the prebuilt files. I put it in my package.json file like this, and then it worked: `"epubjs-rn": "0.0.55",`
At least I didn't get that error, now I have other blob errors.

@fchasen is using gulp pretty important to you? It would make things simpler to eliminate it. I could make a PR, but I don't want to mess up your flow.

**Comment by JulianKingman** [comment]
Ah, right, so part of the problem is that on the readme, it says to do this:
`npm install --save futurepress/epubjs-rn`
Which gets the unbuilt package. If you have this issue, try this:
`npm un epubjs-rn -S && npm i epubjs-rn`

**Comment by fchasen** [comment]
@JulianKingman Thanks for catching that in the readme! Updated.

**Comment by andrewlinfoot** [comment]
looks like you need to add `.babelrc` to the `.npmignore`. They had the same issue here: https://github.com/airbnb/react-native-maps/issues/1206
