### ISSUE TITLE
Chapters redirect problem

### ISSUE THREAD

**Issue by imarem** [futurepress/epubjs-rn#18]
Hello,

I am trying to redirect to the beginning of a chapter, through changing the location of the state. 
I have created a Modal with a chapters lists via book.toc array, and then in onPress I set the new value. 

this.setState({location:item.href});

The first time I press the button, I redirect well to the beginning of the chapter, but when I try to redirect another, it does not show me the correct page or just doesn't load it.

Is this the correct way to redirect? or Is there another way to do these redirects? 
This functionality is present in the plgin? Could you add an example to redirect to the chapters, please?

Thanks!!!

**Comment by fchasen** [comment]
I'll give it a test, it might not be picking up the next location change.

**Comment by imarem** [comment]
Never mind, I updated to 0.0.39 and the problem has been solved! 
I can already redirect to the chapters via locattion without problems!

Thank you!!
