### ISSUE TITLE
When

### ISSUE THREAD

**Issue by julioc96** [futurepress/epubjs-rn#19]
When i tried 

 <Epub src={"https://s3.amazonaws.com/epubjs/books/moby-dick.epub"}
          flow={"paginated"} 	/>   

![captura de pantalla 2017-03-02 a las 11 13 41 a m](https://cloud.githubusercontent.com/assets/4606051/23518448/175061ac-ff39-11e6-872e-a7b5d620db14.png)

I don't understand.

**Comment by fchasen** [comment]
Looks like epubjs isn't picking up the blob polyfill.

You will need to (and should) use the static-server in the EpubReader example to serve a compressed epub.
