### ISSUE TITLE
Change color font css

### ISSUE THREAD

**Issue by imarem** [futurepress/epubjs-rn#20]
Hello,

In the documentation of the plugin I have seen that there is the possibility to generate a themes, and change it.

- themes: JSON object of themes names and css properties to be applied
- theme: Name of the theme to apply, such as light

Could you give an example of how to use the themes, please? I want to change the font color via theme.

Thank you

**Comment by fchasen** [comment]
Themes are still a work in progress but this should work:

```
themes={"custom_name" : { "p" : { "background-color": "purple"}}}
theme="custom_name"
```

**Comment by imarem** [comment]
Thank you man!! it works!
