### ISSUE TITLE
read epub offline/local path

### ISSUE THREAD

**Issue by imarem** [futurepress/epubjs-rn#21]
Hello,

Is there any way I can read the epub offline / or from a local path?

I've been looking at the Stream component, thinking it could be done from this, but the "check" method always returns exists=false.

P.D. I'm running on Android device

Thanks in advance.

**Comment by anoop4real** [comment]
I would also like to know this

**Comment by JulianKingman** [comment]
Same here, here's what my code looks like. I've tried variations of including/excluding the `assets` folder, setting the root explicitly, and using `file://`, nothing seemed to take.
````javascript
import React from 'react';
import { StyleSheet, Text, View, NativeModules } from 'react-native';
import {Epub, Streamer} from 'epubjs-rn';
import ScrollView from 'react-native-visible-scrollview';
import RNFS from 'react-native-fs';

export default class App extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      src: '',
    }

    this.streamer = new Streamer({port: '8899', root: 'assets'});
  }
  
  componentWillMount() {
    this.streamer.start()
    .then((origin) => {
      console.log("Served from:", origin);
      this.streamer.check('http://localhost:8899/Metamorphosis.epub').then((t) => console.log(t));
      return this.streamer.get("http://127.0.0.1:8899/Metamorphosis.epub.zip");
    })
    .then((src) => {
      console.log("Loading from:", src);
      return this.setState({src});
    });
  }

  componentWillUnmount() {
    this.streamer.kill();
  }

  render() {
    const {src} = this.state;
    return (
      <View style={styles.container}>
        <Epub 
          flow={"paginated"} 
          src={src}
        />
      </View>
    );
  }
}
````

**Comment by imarem** [comment]
Hi @fchasen 

Finally I found a small error, in the Stream.js component, which makes when it interrogates if the file exists (via the check method), always return false, and restart de download.

To do this, you must specify the path in RNFetchBlob, when the file download starts.

In Stream.js component, method "add"

`  add(bookUrl) {
    let uri = new Uri(bookUrl);
    const filename = this.filename(bookUrl);
    return RNFetchBlob.config({
      fileCache: true,
      path: Dirs.DocumentDir + '/' + filename // NEW: especify path with epub filename
    }).fetch("GET", bookUrl).then(res => {
      const sourcePath = res.path();
      const targetPath = `${Dirs.DocumentDir}/${this.root}/${filename}`;
      const url = `${this.serverOrigin}/${filename}/`;
      return unzip(sourcePath, targetPath).then(path => {
        this.urls.push(bookUrl);
        this.locals.push(url);
        this.paths.push(path);

       //remove this line for not delete the file from the cache
       // res.flush();

        return url;
      });
    });
  }`

I hope it helps

**Comment by mesismart** [comment]
> > Same here, here's what my code looks like. I've tried variations of including/excluding the `assets` folder, setting the root explicitly, and using `file://`, nothing seemed to take.
> > ```js
> > import React from 'react';
> > import { StyleSheet, Text, View, NativeModules } from 'react-native';
> > import {Epub, Streamer} from 'epubjs-rn';
> > import ScrollView from 'react-native-visible-scrollview';
> > import RNFS from 'react-native-fs';
> > 
> > export default class App extends React.Component {
> >   constructor(props) {
> >     super(props);
> > 
> >     this.state = {
> >       src: '',
> >     }
> > 
> >     this.streamer = new Streamer({port: '8899', root: 'assets'});
> >   }
> >   
> >   componentWillMount() {
> >     this.streamer.start()
> >     .then((origin) => {
> >       console.log("Served from:", origin);
> >       this.streamer.check('http://localhost:8899/Metamorphosis.epub').then((t) => console.log(t));
> >       return this.streamer.get("http://127.0.0.1:8899/Metamorphosis.epub.zip");
> >     })
> >     .then((src) => {
> >       console.log("Loading from:", src);
> >       return this.setState({src});
> >     });
> >   }
> > 
> >   componentWillUnmount() {
> >     this.streamer.kill();
> >   }
> > 
> >   render() {
> >     const {src} = this.state;
> >     return (
> >       <View style={styles.container}>
> >         <Epub 
> >           flow={"paginated"} 
> >           src={src}
> >         />
> >       </View>
> >     );
> >   }
> > }
> > ```
> 
> hey . please help me if posible . my problem is in issue 110




hi vahid , im meisam would u tell me your Email for contact
