### ISSUE TITLE
EPUB.js is not loaded

### ISSUE THREAD

**Issue by valinaga** [futurepress/epubjs-rn#22]
Hey guys,

I almost nailed down the component installation. Here's what I did:
1. add this in package.json in `dependencies:`
`{
   "epubjs-rn": "0.0.41",
    "react-native-fetch-blob": "0.10.2",
    "react-native-fs": "^2.1.0-rc.1",
    "react-native-orientation": "8fit/react-native-orientation",
    "react-native-http-server": "^0.1.2",
    "react-native-visible-scrollview": "0.0.2",
    "react-native-zip-archive": "0.1.0",
    "react-native-vector-icons": "^4.0.0",
    "react-native-static-server": "0.1.3"
}`
2. add to `devDependencies`
`{
    "babel-plugin-module-resolver": "^2.5.0",
    "babel-plugin-static-fs": "^1.1.0",
}`
3. run `npm install && react-native link`
4. for android run `RNFB_ANDROID_PERMISSIONS=true react-native link`

If you follow all the above, the iOS app is working with no problem, assuming you use the code from EpubReader example.

However, same code on android is throwing an error `console.error EPUB.js is not loaded`.
This apparently come from `EpubView.js` from INJECTED_SCRIPT because `EPUBJSContents == undefined`.
Any thoughts on how to solve this issue with Android?
Thanks.

**Comment by valinaga** [comment]
I updated to 0.0.42 but still get same error: `console.error "EPUB.js is not loaded"`.
Any thoughts on this one?
Thanks.

**Comment by valinaga** [comment]
I'm going to buy a beer to the guy who can help fix this issue! :)

**Comment by fchasen** [comment]
What version of Android are you using?

Could you try running with Android studio and checking the Android Monitor for any errors coming from Chrome? 

It sounds like there might just be a javascript error in the webview.

**Comment by valinaga** [comment]
Hi @fchasen,

sorry for long delay. was out of country.
I was testing the reader on a galaxy note using Android 4.3.
Maybe it's too old?
I tried in emulator and it didn't throw that message.

**Comment by valinaga** [comment]
Tested also on an Android 6.0.1 and same thing happened.
`console.error EPUB.js is not loaded.`
It come from EpubView.js from INJECTED_SCRIPT because `EPUBJSContents == undefined`.

**Comment by valinaga** [comment]
Hi @fchasen ,

Any chance to look into the `console.error EPUB.js is not loaded.` error?
It definitely comes from the script injected and somehow the above condition is true: `EPUBJSContents == undefined`.
Thanks for sorting this out.

**Comment by valinaga** [comment]
So I updated to the latest version of everything. It works just fine in iOS and in emulator in Android >5.0, but fails on Android 4.
The error is raised by EpubView.js on line 407 in the method `_onBridgeMessage`.
Apparently the javascript code injected cannot find `EPUB.js`.
Below I paster the whole error stack:
`ExceptionsManager.js:71 EPUB.js is not loaded
reactConsoleErrorHandler	@	ExceptionsManager.js:71
console.error	@	YellowBox.js:62
_onBridgeMessage	@	EpubView.js:407
WebView._this.onMessage	@	WebView.android.js:348
invokeGuardedCallback	@	ReactErrorUtils.js:30
executeDispatch	@	EventPluginUtils.js:99
executeDispatchesInOrder	@	EventPluginUtils.js:127
executeDispatchesAndRelease	@	EventPluginHub.js:37
executeDispatchesAndReleaseTopLevel	@	EventPluginHub.js:48
forEachAccumulated	@	forEachAccumulated.js:32
processEventQueue	@	EventPluginHub.js:226
runEventQueueInBatch	@	ReactEventEmitterMixin.js:18
handleTopLevel	@	ReactEventEmitterMixin.js:38
(anonymous)	@	ReactNativeEventEmitter.js:112
fiberBatchedUpdates	@	ReactGenericBatching.js:27
performFiberBatchedUpdates	@	ReactGenericBatching.js:33
perform	@	Transaction.js:149
batchedUpdates	@	ReactDefaultBatchingStrategy.js:65
batchedUpdates	@	ReactUpdates.js:96
batchedUpdates	@	ReactGenericBatching.js:38
batchedUpdatesWithControlledComponents	@	ReactGenericBatching.js:51
_receiveRootNodeIDEvent	@	ReactNativeEventEmitter.js:111
receiveEvent	@	ReactNativeEventEmitter.js:136
__callFunction	@	MessageQueue.js:244
(anonymous)	@	MessageQueue.js:108
guard	@	MessageQueue.js:46
callFunctionReturnFlushedQueue	@	MessageQueue.js:107
(anonymous)	@	debuggerWorker.js:71`

Any suggestions greately appreciated.
Thanks.

**Comment by valinaga** [comment]
@fchasen 
I tested the Epub component in emulator with different android versions. The output is the following:
1. JellyBean (Android 4.1) - API 16 - I consistently get `EPUB.js is not loaded` as mentioned above.
2. KitKat (Android 4.4) - API 19 - The book is loaded. However after loading the cover, you can only swipe one page. It cannot move beyond page 2. It looks like a scrolling issue since it stop responding for onPress envents. However swiping back works and you get back the second page. Manually setting the location is working and then the subsequent swipes works as well.
3. Lollypop (Android 5.0) - API 21 - It works ok with no apparent issues.
I will open a separate issue for (2) since it doesn't seems to be related to the `EPUBJSContents` issue throwing `EPUB.js is not loaded`.

**Comment by fchasen** [comment]
Could you retest? This should hopefully be fixed.

**Comment by valinaga** [comment]
Hi @fchasen 

The problem is still present for JellyBean, but for the subsequent versions, this issue was fixed.
At least, KitKat and Lollypop is what I tested so far.
Thanks for the update!
