### ISSUE TITLE
[xmldom error]	entity not found:&mdash; 

### ISSUE THREAD

**Issue by valinaga** [futurepress/epubjs-rn#27]
test book: https://m.cevadesign.ro/humanitas/Selma_Lagerlof_Imparatul_Portugaliei.epub

Swiping for second page will raise an exception from the `dom.parser.js` with error `entity not found:&mdash; `.
Apparenly the &mdash;  (`&mdash;`) is not defined in the `entityMap` list of `DOMParser.prototype.parseFromString`. 
Is there a way to add more entities like this one?
Thanks.

**Comment by valinaga** [comment]
To fix this: edit `node_modules/xmldom\dom-parser.js` and at line 3 add your exceptions in `entityMap`.
Example: `'shy': '', 'mdash': '-'`.
This fixed my issue.

**Comment by valinaga** [comment]
TO fix this, add this to your package.json
`"xmldom": "https://github.com/valinaga/xmldom.git"`

**Comment by fchasen** [comment]
Might be good to raise that issue here: https://github.com/jindw/xmldom/issues

**Comment by valinaga** [comment]
@fchasen I'll do that. Thanks.

**Comment by fchasen** [comment]
This is going to need to be fixed in epub.js / xmldom.

xhtml is reported with a mimetype of `"application/xhtml+xml"` but the xmldom regex doesn't pick it up.

https://github.com/jindw/xmldom/blob/ffd8cac8f65a56286bc654946aaaa49620018d49/dom-parser.js#L13

It should be `/\/x?html?(\+xml)?$/`

**Comment by fchasen** [comment]
PR here: https://github.com/jindw/xmldom/pull/208

I'll update epub.js to temporally refer to my fork with the fixes.
