### ISSUE TITLE
Android: EPUB.js is not loaded

### ISSUE THREAD

**Issue by valinaga** [futurepress/epubjs-rn#28]
On this new release I consistently get `EPUB.js is not loaded` on any version of Android, old or new.
I tested with 4.3, 5.0, 6.0.
The output in chrome debug until the error was raised:
`inital orientation PORTRAIT 360 640`
`http://localhost:43753/moby-dick/`
`loading book:  http://localhost:43753/moby-dick/`
`book opened 303`
`displaying 1`
`visibility 1 true`
`EPUB.js is not loaded`
The book was downloaded correctly and was streamed ready.
The issue appears in the `INJECTED_SCRIPT` in `EpubView.js` around line 23 on condition: 
`typeof EPUBJSContents === "undefined"`.

@fchasen, is there a way I can help? any suggestion on where to look for this `EPUBJSContents`?
Thanks.

**Comment by fchasen** [comment]
This was fixed in https://github.com/futurepress/epubjs-rn/commit/452ac101722d9063f068d325b6e5f084489e7f57. It was a javascript error in Android as the `marks-pane` library was not being transpiled from es6.
