### ISSUE TITLE
IOS Crash: Message from debugger: Terminated due to memory issue

### ISSUE THREAD

**Issue by valinaga** [futurepress/epubjs-rn#31]
Only on acutal device. Does not happens in emulator.
When I want to change the font size in Epub the app crash with this error:
`Message from debugger: Terminated due to memory issue`
The code to crash is simple:  `this.setState({ fontSize: 18 })` for any value of fontSize.

**Comment by valinaga** [comment]
The issue above does not manifest anymore in version 0.0.64 with rn 0.44.2.
Thanks.

**Comment by fchasen** [comment]
I started to see the same issue on ios on longer books, where if you increased the font size it would crash but if you decreased it the book was fine.

Seems that after a certain very large width or height, UIWebViews just crash.
https://stackoverflow.com/questions/28673505/uiwebview-with-dynamic-height-leads-to-memory-crash

The limit for me seems to be around 100,000 pixels.

Switching to WKWebview on IOS seems to fix this and bring a few other memory / speed improvements as well.

https://github.com/futurepress/epubjs-rn/pull/32
