### ISSUE TITLE
Can't find variable: URL

### ISSUE THREAD

**Issue by StasVitAlex** [futurepress/epubjs-rn#36]
Have this issue:
![image](https://user-images.githubusercontent.com/20992730/27835764-1281cbda-60e5-11e7-8f99-5c459540af4b.png)

**Comment by fchasen** [comment]
Thanks, this should be fixed in `epubjs-rn@0.0.79`

**Comment by veeyka** [comment]
> Thanks, this should be fixed in `epubjs-rn@0.0.79`

pls can you answer 110 issue ? if possible
