### ISSUE TITLE
How to control the column width or the number of columns ?

### ISSUE THREAD

**Issue by valinaga** [futurepress/epubjs-rn#38]
When in landscape mode on Samsung A5, the layout has 2 columns instead of 1 and it looks bad.
On IOS on iPhone 6, in landscape mode there's only one column, which is ok.
Please help.

**Comment by imarem** [comment]
Hi @valinaga 

You can modify the minSpreadWidth parameter from Epub.js , for example increasing to 850, devices like samsung A5, does not apply to two columns.

Hope this help you.

**Comment by valinaga** [comment]
@imarem Thanks a lot! will try that.
