### ISSUE TITLE
How to change font

### ISSUE THREAD

**Issue by imarem** [futurepress/epubjs-rn#39]
Hello,

In the documentation of the plugin I have seen that there is the possibility to change the font-family
"font: CSS override for font family"

I have tried with several fonts type Verdana, Arial, etc but the style does not apply.

Is this functionality currently implemented? Could you give an example of how to use font, please?

Thank you

**Comment by fchasen** [comment]
Should work by just adding the font-family string you define to the body of the book chapter.

It's possible the book has more specific font definitions that it isn't able to override.
