### ISSUE TITLE
Read epub offline.

### ISSUE THREAD

**Issue by MustansirZia** [futurepress/epubjs-rn#44]
Hi @fchasen 
I'm currently working on a project and I'm trying my best to integrate offline reading. I use [react-native-fetch-blob](https://github.com/wkh237/react-native-fetch-blob) to download an epub file to my phone. Now once I give a local path to the Streamer with or without the `file://` it shows this error 
`Error: RNFetchBlob request error: unexpected url: file:///data/data/com.app.reader/files/sample.epub`
I believe this issue was brought up [here #12 ](https://github.com/futurepress/epubjs-rn/issues/12).
The solution mentioned there doesn't work sadly.

It was also brought up [here #21](https://github.com/futurepress/epubjs-rn/issues/21)

Hoping you'd take a look. Thanks!

**Comment by MustansirZia** [comment]
Here's my version of the code 
```js
async componentDidMount() {
        try {
            const book = await booksDB().findOne(this.props.bookID).exec();

            this.book = book;

            const origin = await this.streamer.start("8899");
            console.log("Served from:", origin);
            
            // book.getSource() returns file:///data/data/com.app.reader/files/sample.epub
            const src = await this.streamer.get(book.getSource());
            // alert("Loading from: " + src);

            this.setState({origin, src, currentCFI: book.currentCFI});

        } catch (err) {
            console.warn(err);
            this.showToast('Experiencing issues. Try again.');
        }
    }
```

**Comment by imarem** [comment]
Hi,

you must specify the path, in the Streamer.js component. Follow my code described in https://github.com/futurepress/epubjs-rn/issues/21

Currently I can read epubs offline without problems.

Hope it helps

**Comment by MustansirZia** [comment]
@imarem You're asking me to alter the library, yes?

**Comment by imarem** [comment]
Exactly

**Comment by MustansirZia** [comment]
Lemme try!

**Comment by MustansirZia** [comment]
I changed the add method as you described and added a `fil://...` link to get method but it's the same as before. Can you please show me your whole of Streamer.js?

**Comment by imarem** [comment]
Hi @MustansirZia,

I think **you can not directly use a path to a file**, passing a local path will not work as the assets need to be served to the webview. 
Currently with the code that exists, you must use a url to perform the first download of epub. Once downloaded and cached, when opening again with that same url, the system will check if it exists and if it, doesn't download it again.

Look carefully, "get" and "check" functions from streamer.js.

Applying the changes I mentioned, you could test with moby-dick.epub url from the exemple code. And you'll see how the second time you go offline (you can put the device in airplanemode) the epub opens correctly from cache file sistem.

Hope it helps

**Comment by valinaga** [comment]
@imarem 
The problem with the file is that RNFetchBlob (line 65-68) will always generate temporary, thus different files upon download. That means that caching is pointless. Also, the file is deleted after expanding (line 83), so again, it does not matter.
I think that the streamer can be modified to look for the unzip directory, which is preserving the original file name. The `targetPath` (line 92) should point to the unzip directory `(${Dirs.DocumentDir}/${this.root}/${filename}; )`. 
Anyway, I cloned and modified my own version of Streamer.js so I can cache the file with original name and also check the existence of the unzip dir.
A good ideea is to take out the downloading and expanding the book and use it for background syncing.

**Comment by imarem** [comment]
@valinaga 
Exactly, I have my version of Streamer.js too. I change my add function and looks like [https://github.com/futurepress/epubjs-rn/issues/21](url)

**Comment by MustansirZia** [comment]
@imarem I really should thank you! It worked like a charm. I was thinking about it the wrong way. The epub file is now cached. Thanks again!

**Comment by MustansirZia** [comment]
Now, should we close this issue or leave it open since there's definitely a bug inside Streamer.js?

**Comment by fchasen** [comment]
Updated the streamer to reflect https://github.com/futurepress/epubjs-rn/issues/21 in 0.0.96
