### ISSUE TITLE
Version 0.0.93: Android pagination error

### ISSUE THREAD

**Issue by vegmorse** [futurepress/epubjs-rn#45]
Hi @fchasen 

The pagination on Android does not work properly. Don't stop at each page.

In iOS it works perfectly, I think it's for using WKWebView with the pagingEnabled=true property.

Do you think it's possible to adapt the latest version to work with a single webview for both platforms?

Thanks in advance.

**Comment by imarem** [comment]
Same here :(

**Comment by valinaga** [comment]
Maybe this can help.

https://stackoverflow.com/questions/18964259/how-to-split-up-epub-html-into-pages-according-to-screen-size

**Comment by fchasen** [comment]
Thanks for reporting, I'm thinking the best way to address this is by using a scroll snap polyfill in the webview like the this one: https://github.com/ckrack/scrollsnap-polyfill

Unfortunately It seems that it will need a few changes to work on the body element, so I'm working on that now.

**Comment by valinaga** [comment]
@fchasen Hi, 

Any news on the pagination issue? Can I (we) help in any ways?
Thanks.

**Comment by fchasen** [comment]
Should have updates on this next week.

**Comment by AntonDatsik** [comment]
@fchasen 
Hi, how much time do you need for fix this bug? Can we help you?

**Comment by fchasen** [comment]
Can you give the `android_pagination` branch a try. I think the functionality is mostly done but will need some performance tweaks.

**Comment by valinaga** [comment]
@fchasen I tried to install this branch but something is broken. After adding the package I keep getting the error `Unable to resolve module 'epubrn-js' Module does not exist in the module map`.
I also cloned the repository and updated the `bridge.js` and still got the same error. It seems that something in the bridge.js is breaking the module.
Any idea?

**Comment by imarem** [comment]
Hi @fchasen ,

After install the new branch for android_pagination, and execute `gulp build` for render the package in a components folder, when I open the epub, only showns the spinner loading. It seems that something is broken in the branch, 

Could you check it out? or on the other side, when you have planned merge in the master? 

Thanks in advance.

**Comment by imarem** [comment]
@fchasen 

Thanks you so much for the last release!!! Now Android pagination works like a charm!!

Thank you!!!!

**Comment by vegmorse** [comment]
@fchasen thanks for the update!

For me, you can close the issue.

**Comment by StasVitAlex** [comment]
Not agree,  for me on phones it is working with bugs
Also after this fix text is not selecting

**Comment by fchasen** [comment]
@StasVitAlex Sorry to hear this isn't working, can you open a new issue with some more info on the bugs you are experiencing on phones?

**Comment by StasVitAlex** [comment]
@fchasen, thnx
We solved android pagination issue in forked version
