### ISSUE TITLE
fontSize issue

### ISSUE THREAD

**Issue by valinaga** [futurepress/epubjs-rn#46]
Hi

It seems that between 0.0.79 and 0.0.93 setting the font size does not work anymore.
Initial setting is taken but subsequent renderings with different fontSize are not being processed.
Any idea on where to fix this?

EDIT: I looked into the code in Rendition.js and the method this.sendToBridge("font", [f]); is always called then the font changes. So it looks like the issue is in the native part.
I also checked and the rendition is also re-rendered each time the font is set.

Thanks.

**Comment by imarem** [comment]
Hi @valinaga 

It seems that in the last version, you need specify the size as a string like "17px" or "19px" for example.
By this way, the fontSize is applied correctly.

**Comment by fchasen** [comment]
Yep, it needs to include the units now so that you can also adjust it using other units such as ems.

I'll double check that setting it after the initial render works.

**Comment by valinaga** [comment]
@imarem Thanks!
@fchasen we can close this issue. 
Thanks.
