### ISSUE TITLE
Epub doesn't load when appState change from background to active

### ISSUE THREAD

**Issue by imarem** [futurepress/epubjs-rn#48]
Hi,

When static server goes from background to active, the epub doesn't expand any more. Only load the pages for which it has expanded before.

I think the problem is in react-native-static-server, and the eventListners for AppState. Why you should the server stop when it goes in the background? Is it due to problems in terms of memory?

Thanks in advance.

**Comment by fchasen** [comment]
Starting and stopping the server seems like the right approach, since it should be easy enough to resume serving the file once they are needed again.

I'm not seeing any issues switching from background to active on iOS or Android. Could you describe your setup a bit more?

**Comment by imarem** [comment]
Hi @fchasen ,

After upgrade to latest version the problem doesnt apear any more.

I close the issue

Thanks.
