### ISSUE TITLE
Next page and prev page methods

### ISSUE THREAD

**Issue by AntonDatsik** [futurepress/epubjs-rn#50]
Hi, is it possible to navigate to next page and previous page?

**Comment by StasVitAlex** [comment]
Interesting for me too

**Comment by valinaga** [comment]
I think that rendition.next() and rendition.prev() are doing what you're looking for. Just export these methods and you're done.

**Comment by AntonDatsik** [comment]
@valinaga 
Hi!
rendition.next() not working for me(
Error: rendition.next is not a function
I create a ref={(epub) => this.epub = epub}
And after that I try to get rendition object in this.epub.rendition

**Comment by valinaga** [comment]
Make sure you get the rendition correctly. Maybe you can get it from onPress and store it in your class.

**Comment by AntonDatsik** [comment]
@valinaga 
Are you sure that rendition object has next() and prev() methods?
Rendition object which I get from onPress method doesn't have this methods.
And I didn't find this methods in Rendition component code.

**Comment by valinaga** [comment]
I saw this in ePub.js examples v3. Never actually tested. You can take a look also.

**Comment by fchasen** [comment]
I'm not currently passing prev / next to the webview since swipe seemed to be the main way of interacting with the page, but would be simple enough to add. What are you using prev and next page calls for?

**Comment by AntonDatsik** [comment]
Now, I change location. For next method I use book.locations.cfiFromPercentage(currentLocation.end.percentage)
And for the prev method I use
currentLocation.start.cfi
But it is not clear and sometimes doesn't work properly(For example after resizing).

**Comment by Vilitsa** [comment]
It will be very helpfull if you add prev and next methods. I need to create click area for go ti prev and next page.

**Comment by SurpassRabbit** [comment]
I will hope add prev and next methods.  thanks
