### ISSUE TITLE
Get pages count

### ISSUE THREAD

**Issue by AntonDatsik** [futurepress/epubjs-rn#51]
Hi, is it possible to get total pages count?

**Comment by valinaga** [comment]
Looks like locations contain a field named total which is the total page number. Current page is just percentage * total. 
Just make sure you get the percentage correctly. 
Best way is to dive in ePub.js (v3) examples for inspiration.

**Comment by AntonDatsik** [comment]
@valinaga 
I opened book on different devices, and total field in locations doesn't depends of the screen size.
The total field is constant for book. And of course, devices are different and count of pages should be different too.

**Comment by fchasen** [comment]
Thats correct, generating the actual pages means rendering out each chapter so we use location that are based on a character count of text instead (much like Adobe Digital Editions)

**Comment by matikups** [comment]
I'm sorry, I'm interest on this as well.

Could we please not close the issues unless there's a clear answer?
