### ISSUE TITLE
BUG: onPress or onLongPress function props are required

### ISSUE THREAD

**Issue by StasVitAlex** [futurepress/epubjs-rn#53]
If i remove onPress and onLongPress props from Epub component or will bind functions for them in constructor and call them like onPress={this.onPressed}, epub stops updating locations(

**Comment by MustansirZia** [comment]
You mean the `onLocationChange` is not getting called?

**Comment by StasVitAlex** [comment]
Book doesn't change location(page), and of course onLocationChange  is not getting called

**Comment by MustansirZia** [comment]
Book is changing the page but the `onLocationChange` handler isn't getting called. I'm opening a new issue for `onLocationChange`.

**Comment by fchasen** [comment]
I'm not able to reproduce this
