### ISSUE TITLE
BUG: Cannot read property 'themes' of undefined

### ISSUE THREAD

**Issue by imarem** [futurepress/epubjs-rn#59]
Hi,

In previous versions I had some themes defined like that:
  ```
themes={{
            "white": { "body": { "background-color": "white !important", "line-height":"1.7!important"}, 
              "p": { "background-color": "white !important","color": 'black !important',}, 
              "h1": { "background-color": "white !important","color": 'black !important' }, 
              "h2": { "background-color": "white !important","color": 'black !important' }, 
              "h3": { "background-color": "white !important","color": 'black !important' }, 
              "h4": { "background-color": "white !important","color": 'black !important' }, 
              "div": { "background-color": "white !important","color": 'black !important' }, 
              "span": { "background-color": "white !important","color": 'black !important'}},
            "beige": { "body": { "background-color": "#dcc7a1 !important", "line-height":"1.7"}, 
              "p": { "background-color": "#dcc7a1 !important","color": '#595959 !important'}, 
              "h1": { "background-color": "#dcc7a1 !important","color": '#595959 !important' }, 
              "h2": { "background-color": "#dcc7a1 !important","color": '#595959 !important' }, 
              "h3": { "background-color": "#dcc7a1 !important","color": '#595959 !important' }, 
              "h4": { "background-color": "#dcc7a1 !important","color": '#595959 !important' }, 
              "div": { "background-color": "#dcc7a1 !important","color": '#595959 !important' }, 
              "span": { "background-color": "#dcc7a1 !important","color": '#595959 !important' }},
            "grey": { "body": { "background-color": "#595959 !important", "line-height":"1.7"}, 
              "p": { "background-color": "#595959 !important","color": '#dcc7a1 !important'}, 
              "h1": { "background-color": "#595959 !important","color": '#dcc7a1 !important' }, 
              "h2": { "background-color": "#595959 !important","color": '#dcc7a1 !important' }, 
              "h3": { "background-color": "#595959 !important","color": '#dcc7a1 !important' }, 
              "h4": { "background-color": "#595959 !important","color": '#dcc7a1 !important' }, 
              "div": { "background-color": "#595959 !important","color": '#dcc7a1 !important' }, 
              "span": { "background-color": "#595959 !important","color": '#dcc7a1 !important' } },
            "black": { "body": { "background-color": "#191919 !important", "line-height":"1.7"}, 
              "p": { "background-color": "#191919 !important","color": 'white !important'}, 
              "h1": { "background-color": "#191919 !important","color": 'white !important' }, 
              "h2": { "background-color": "#191919 !important","color": 'white !important' }, 
              "h3": { "background-color": "#191919 !important","color": 'white !important' }, 
              "h4": { "background-color": "#191919 !important","color": 'white !important' }, 
              "div": { "background-color": "#191919 !important","color": 'white !important' }, 
              "span": { "background-color": "#191919 !important","color": 'white !important' } }
          }}
theme={this.state.theme}
```

And changing through the theme property with state like this.setState({theme:'black'), and works fine.

Now when I open the epub, I get this error.
![screenshot_20170901-130354](https://user-images.githubusercontent.com/4670453/29967329-79c2675a-8f16-11e7-9e0d-b90833874484.png)

Any ideas for how to fix this bug?

Thanks.

**Comment by valinaga** [comment]
Had the same issue, but somehow it vanished after playing with themes and theme.
The theme must me one of white, beige, grey...  in your case, I think.
I only have one theme but I don't use "" around the name.
`          themes={{
            custom: { '*': { '-webkit-user-select': 'none' }, img: { 'margin-top': '45px' } }
          }}
`
and

`theme="custom"`
Maybe you can fix your case.

**Comment by imarem** [comment]
Hi @valinaga 

I've tried what you've suggested, but the result is the same. I've removed all "", from names and classes.

When I try with the debugger, the error does not appear to me. It seems a problem related to the pass of paramters through the props, by the error that appears to me (detailed in the capture)

On the other hand the change from one topic to the other works me correctly. So the main problem is reproduced at the end of loading the epub.

**Comment by valinaga** [comment]
Yes, you're right. It looks like somehow it does not manifest on iOS, but on Android. And I updated to the latest 0.0.103, which test for rendition before registering themes in bridge.js.
It's pretty annoying to have things fixed while other seems to broke.

**Comment by imarem** [comment]
Thanks @valinaga 

After upgrade to 0.0.103, error doesn't show.

> It's pretty annoying to have things fixed while other seems to broke.

And totally agree, in my opinion, version 0.0.96, was the last stable version. If the pagination for Android devices had been implemented, it would have been a full version for my purpose.

Now I have another bug similar with themes. [https://github.com/futurepress/epubjs-rn/issues/60](https://github.com/futurepress/epubjs-rn/issues/60)

Anyway, thanks for fixing this bug @fchasen, I close it.
