### ISSUE TITLE
Reader move to prev page, when change width property

### ISSUE THREAD

**Issue by AntonDatsik** [futurepress/epubjs-rn#61]
Hi, I have a sidebar which can be opened or closed.
When I open and close sidebar book goes to the previous page(sidebar toggling cause changing width property for Epub component). And after opening and closing sidebar book goes to the previous page.
It doesn't happens when book is open on start chapter page.

**Comment by fchasen** [comment]
It assigns the last read position to be the upper left hand corner of the page, so when the width shrinks that location might be on the previous page. I'd recommend having the sidebar positioned on top of the epub so that it does not cause rerenders.
