### ISSUE TITLE
android_pagination branch instalation

### ISSUE THREAD

**Issue by valinaga** [futurepress/epubjs-rn#62]
Anyone able to install the `android_pagination ` branch?
I was not able to do this, even after cloning the repo on my side and installed from the master branch. 
It keeps saying that `epubjs-rn` was not found in the modules map.
Any suggestion?
Thanks.

**Comment by imarem** [comment]
Hi @valinaga,

I can't try it the branch yet, but i think that you need execute "gulp build" on the root of the epubjs-rn in the node_modules to compile all the files in the components folder.

Next week I work on this!!

**Comment by fchasen** [comment]
Yes that is correct, you'll need to build the components with `gulp build` before you can test it locally from a branch.

**Comment by valinaga** [comment]
@fchasen was this branched finally merged?
the issue doesn't seems to be fixed in the latest release.
