### ISSUE TITLE
Weird imports, Dimensions, ReactNative

### ISSUE THREAD

**Issue by JulianKingman** [futurepress/epubjs-rn#8]
`Epub.js` and `EpubViewManager.js` try to import strange modules that don't appear to exist. For example `import Dimensions from "Dimensions"` (should be `react-native`?), and `import ReactNative from "ReactNative"`, also `NativeModules`. My guess is this has to do with the version of react-native?

**Comment by timojaask** [comment]
I was experiencing the same problem. Submitted a fix: https://github.com/futurepress/epubjs-rn/pull/9

**Comment by fchasen** [comment]
Fixed in v0.0.33
