### ISSUE TITLE
bundle load failed

### ISSUE THREAD

**Issue by memosize** [futurepress/epubjs-rn#87]
in node modules masks-pane ''could not find preset ''es2015"

**Comment by starkyru** [comment]
Use `yarn add babel-preset-es2015 -D`

**Comment by fchasen** [comment]
I'm not sure why you are getting that error, `marks-pane` has the babel preset as a dependency here: https://github.com/fchasen/marks/blob/master/package.json#L24

Can you check the version that was added in your `node_modules`?

**Comment by memosize** [comment]
yarn add babel-preset-es2015 -D can resolve ths

**Comment by fchasen** [comment]
`marks-pane` need to have it's `.babelrc` in npmignore. Fixed in `epubjs-rn@0.0.118`.
