### ISSUE TITLE
Custom font

### ISSUE THREAD

**Issue by HDSnarathorn** [futurepress/epubjs-rn#89]
There is a way to use my custom font (otf) instead of verdana,arial,strix?
Should I use theme/stylesheet or font?

Thanks

**Comment by fchasen** [comment]
You could apply font to the appropriate elements (p, h1, ect) in a theme or you could load in a custom stylesheet.

The font will need to be accessible at a URL, which could be remote or served locally from the Streamer.

**Comment by veeyka** [comment]
> You could apply font to the appropriate elements (p, h1, ect) in a theme or you could load in a custom stylesheet.
> 
> The font will need to be accessible at a URL, which could be remote or served locally from the Streamer.

hey man . can you helo me in issue 118
