### ISSUE TITLE
How to get selected text value within onSelected handler?

### ISSUE THREAD

**Issue by Dalamar** [futurepress/epubjs-rn#91]
Hi!

Please advise how to accomplish getting a value of selected text and assign event listener on selected text press in the following scenario:

### Part I
**Action:**
* User selects some range of text in the book.

**Result:**
* Selected text is being highlighted (this part is done)
* Selected text is assigned to app state variable
* Event listener assigned to a selected text

### Part II
**Action:**
* User taps the highlighted text

**Result**
* Selected text event handler is being triggered.

**Comment by dwidjaja945** [comment]
I am also having this same issue.
What have you tried so far?

I have tried taking the event of `onPress` but it does not provide the text of the event.

**Comment by fchasen** [comment]
The `onMarkClicked` property should be the event handler you are looking for.
