### ISSUE TITLE
EPUBJS-Webview Uncaught TypeError: Object.assign is not a function

### ISSUE THREAD

**Issue by viet0511** [futurepress/epubjs-rn#95]
I try to build and run example with react-native but caught error in console:

> EPUBJS-Webview Uncaught TypeError: Object.assign is not a function

My dependencies:
"dependencies": {
    "@babel/preset-env": "^7.0.0-rc.1",
    "base-64": "^0.1.0",
    "epubjs": "^0.3.66",
    "epubjs-rn": "0.0.124",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-fs": "^2.11.15",
    "react-native-orientation": "^3.1.3",
    "react-native-static-server": "^0.3.0",
    "react-native-vector-icons": "^5.0.0",
    "react-native-wkwebview-reborn": "^1.21.0",
    "react-native-zip-archive": "^2.2.6"
  }

How to solve that issue?

**Comment by fchasen** [comment]
Are you running it on iOS or Android and what version of the device are you using?

**Comment by viet0511** [comment]
I'm running on Android AVD with API 23, Android 6.0 then it caugh error.

PS: After that i try on real device: Samsung Note FE  Android version: 8.0.0 it work properly.

What happen with my AVD?

**Comment by viet0511** [comment]
Finally found it. Android 6.0 Webview doesn't support Object.assign.
Can you add polyfill for Object.assign before load epubjs?

**Comment by ilonny** [comment]
please add polyfill.

**Comment by yabeow** [comment]
yeah i face this issue too, please add polyfill :(

**Comment by yabeow** [comment]
Check out this pull request: https://github.com/futurepress/epubjs-rn/pull/107

**Comment by matikups** [comment]
@yabeow tried that and didn't work
any ideas?

**Comment by yabeow** [comment]
> @yabeow tried that and didn't work
> any ideas?

What Android version did you test it on? For me, it works for Android 5.0 and above.

**Comment by matikups** [comment]
Android 5.0 and above too :/
I actually added this by hand with no luck :|
